
```{r}
# Instalar las librerías (solo es necesario la primera vez)
install.packages("data.table")
install.packages("rpart")
install.packages("rpart.plot")
```

```{r}
# Cargar las librerías
require(data.table)
require(rpart)
require(rpart.plot)

```



```{r}
# cargo el dataset que tiene la clase calculada !
dataset <- fread("G:/Mi unidad/1- DM en Economía y Finanzas - Lunes y Jueves/Clase ternaria/competencia_01_con_clase_ternaria.csv")
```


```{r}
# Verificar el contenido del dataframe
head(dataset)
```


```{r}
dtrain <- dataset[foto_mes <= 202104] # defino donde voy a entrenar
dapply <- dataset[foto_mes == 202106] # defino donde voy a aplicar el modelo
```


```{r}
# genero el modelo,  aqui se construye el arbol
# quiero predecir clase_ternaria a partir de el resto de las variables
modelo <- rpart(
    formula = "CLASE_TERNARIA ~ .",
    data = dtrain, # los datos donde voy a entrenar
    xval = 0,
    cp = -1, # esto significa no limitar la complejidad de los splits
    minsplit = 250, # minima cantidad de registros para que se haga el split
    minbucket = 100, # tamaño minimo de una hoja
    maxdepth = 7  # profundidad maxima del arbol
)
```



```{r}
# grafico el arbol
prp(modelo,
    extra = 101, digits = -5,
    branch = 1, type = 4, varlen = 0, faclen = 0
)
```


```{r}
# aplico el modelo a los datos nuevos
prediccion <- predict(
    object = modelo,
    newdata = dapply,
    type = "prob"
)
```


```{r}
# prediccion es una matriz con TRES columnas,
# llamadas "BAJA+1", "BAJA+2"  y "CONTINUA"
# cada columna es el vector de probabilidades

# agrego a dapply una columna nueva que es la probabilidad de BAJA+2
dapply[, prob_baja2 := prediccion[, "BAJA+2"]]

# solo le envio estimulo a los registros
#  con probabilidad de BAJA+2 mayor  a  1/40
dapply[, Predicted := as.numeric(prob_baja2 > 1 / 40)]
```


```{r}
# genero el archivo para Kaggle
# primero creo la carpeta donde va el experimento
dir.create("./exp/")
dir.create("./exp/KA2001")
```

```{r}
# solo los campos para Kaggle
fwrite(dapply[, list(numero_de_cliente, Predicted)],
        file = "./exp/KA2001/v003-TP1_solucion.csv",
        sep = ","
)
```











